name: Lint Markdown files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-markdown:
    name: Check Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint changelog file
        uses: avto-dev/markdown-lint@v1
        with:
          args: '**/*.md'

      - name: Check changelog file exists
        id: check_changelog
        uses: andstor/file-existence-action@v1
        with:
          files: "./CHANGELOG.md"

      - name: Lint changelog file
        if: steps.check_changelog.outputs.files_exists == 'true'
        uses: avto-dev/markdown-lint@v1
        with:
          rules: '/lint/rules/changelog.js'
          config: '/lint/config/changelog.yml'
          args: './CHANGELOG.md'
